version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: manager
      POSTGRES_DB: scheduling
    ports:
      - '5433:5432'
    volumes:
      - data_pg:/var/lib/postgresql/data

volumes:
  data_pg: